export const IS_PLAY_BAR_DISPLAYED = "IS_PLAY_BAR_DISPLAYED";
export const IS_PLAYING = "IS_PLAYING";
export const TRACK_OBJECT = "TRACK_OBJECT";
export const WAVESURFER_PROPERTIES = "WAVESURFER_PROPERTIES";
export const SET_POSITION_IN_HISTORY = "SET_POSITION_IN_HISTORY";
export const RELOAD_FETCH = "RELOAD_FETCH";
