export const IS_PLAY_VAR_DISPLAYED = "IS_PLAY_VAR_DISPLAYED";
export const IS_PLAYING = "IS_PLAYING";
export const NOT_PLAY_VAR_DISPLAYED = "NOT_PLAY_VAR_DISPLAYED";
export const NOT_PLAYING = "NOT_PLAYING";
export const TRACK_OBJECT = "TRACK_OBJECT";
