export const SHOW_DIALOGUE = "SHOW_DIALOGUE";
export const HIDE_DIALOGUE = "HIDE_DIALOGUE";
export const SHOW_UPDATE_MODAL = "SHOW_UPDATE_MODAL";
export const SHOW_DELETE_MODAL = "SHOW_DELETE_MODAL";
export const SHOW_MY_PLAYLIST = "SHOW_MY_PLAYLIST";
